import { Button } from '@starter/ui';

export function HomePage() {
  return (
    <section className="space-y-4">
      <h1 className="text-3xl font-bold">
        <bdi dir="ltr" lang="en">
          NX AI Pipeline
        </bdi>
      </h1>
      <p className="text-muted">ברוכים הבאים לאתר הבדיקה של הצינור</p>
      <div className="flex flex-wrap items-center gap-3">
        <Button>התחילו כאן</Button>
        {/* Static page generated by deploy.yml; not a router route, so a plain
            link through BASE_URL (works under /<repo>/ on Pages). */}
        <a
          href={`${import.meta.env.BASE_URL}code-map/`}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 rounded-lg border border-brand-100 bg-brand-50 px-4 py-2 font-medium text-brand-700 transition-colors hover:bg-brand-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-500"
        >
          מפת קוד
          <span className="sr-only">(נפתח בלשונית חדשה)</span>
        </a>
      </div>
    </section>
  );
}
