// Renders the model as Markdown with a Mermaid flowchart (GitHub renders it
// natively). Output is unformatted; generate.mjs runs Prettier over it.
import { triggerText } from './workflows.mjs';

const CLASS_DEFS = {
  stage: 'fill:#e3f2fd,stroke:#1565c0,color:#0d47a1',
  workflow: 'fill:#f5f5f5,stroke:#616161,color:#212121',
  gate: 'fill:#f5f5f5,stroke:#616161,color:#212121,stroke-dasharray:4 3',
  problem: 'fill:#ffebee,stroke:#c62828,color:#b71c1c',
  human: 'fill:#fff8e1,stroke:#ff8f00,color:#e65100',
  loop: 'fill:#e0f2f1,stroke:#00897b,color:#004d40',
};
const LINK_STYLES = {
  problem: 'stroke:#c62828,stroke-width:2px',
  loop: 'stroke:#00897b,stroke-width:2px',
  human: 'stroke:#ff8f00',
};
const SHAPES = {
  round: ['(', ')'],
  rect: ['[', ']'],
  hex: ['{{', '}}'],
  stadium: ['([', '])'],
  flag: ['>', ']'],
};

const quote = (s) => `"${String(s).replace(/"/g, '#quot;')}"`;
const code = (s) => `\`${s}\``;
const cell = (items) => (items.length ? items.join(', ') : '-');

export function renderMermaid(model) {
  const lines = ['flowchart TD'];
  for (const n of model.nodes) {
    const [open, close] = SHAPES[n.shape];
    lines.push(`  ${n.id}${open}${quote(n.text)}${close}`);
  }
  model.edges.forEach((e) => {
    const arrow = e.kind === 'problem' ? '-.->' : '-->';
    const label = e.label ? `|${quote(e.label)}|` : '';
    lines.push(`  ${e.from} ${arrow}${label} ${e.to}`);
  });
  for (const [cls, style] of Object.entries(CLASS_DEFS))
    lines.push(`  classDef ${cls} ${style}`);
  for (const cls of Object.keys(CLASS_DEFS)) {
    const ids = model.nodes.filter((n) => n.cls === cls).map((n) => n.id);
    if (ids.length) lines.push(`  class ${ids.join(',')} ${cls}`);
  }
  for (const [kind, style] of Object.entries(LINK_STYLES)) {
    const idx = model.edges.flatMap((e, i) => (e.kind === kind ? [i] : []));
    if (idx.length) lines.push(`  linkStyle ${idx.join(',')} ${style}`);
  }
  return lines.join('\n');
}

function gateText(g) {
  return [
    ...g.labels.map(code),
    ...g.prefixes.map((p) => {
      const except = g.excluded.filter((l) => l.startsWith(p));
      return `any ${code(`${p}*`)}${except.length ? ` except ${except.map(code).join(', ')}` : ''}`;
    }),
    ...g.statusContexts.map((c) => `status ${code(c)}`),
    ...g.runConclusions.map((c) => `run ${code(c)}`),
  ];
}

function workflowTable(model) {
  const rows = model.workflows.map((w) => {
    const normal = (s) => w.writes.some((x) => x.stage === s && !x.problem);
    const all = [...new Set(w.writes.map((x) => x.stage))].sort();
    const stages = [
      ...all.filter(normal).map(code),
      ...all.filter((s) => !normal(s)).map((s) => `${code(s)} (escalation)`),
    ];
    const markers = [...new Set(w.markerWrites.map((m) => m.key))].sort();
    return `| ${code(w.file)} | ${cell(w.triggers.map((t) => code(triggerText(t))))} | ${cell(gateText(w.gates))} | ${cell(stages)} | ${cell(markers.map(code))} |`;
  });
  return [
    '| Workflow | Trigger | Gate (job `if:`) | Stages set | Comment markers |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function markerTable(model) {
  const rows = model.markerWriters.map(({ key, marker, writers }) => {
    const by = writers.map(
      ([file, cmds]) => `${code(file)} (${cmds.map(code).join(', ')})`,
    );
    return `| ${code(marker)} | ${code(key)} | ${cell(by)} |`;
  });
  return [
    '| Marker | Key | Written by (workflow, `pipeline.mjs` command) |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function ungatedTable(model) {
  const rows = Object.entries(model.expectedUngated)
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([s, cfg]) => `| ${code(s)} | ${cfg.kind} | ${cfg.reason} |`);
  return [
    '| Stage | Kind | Why nothing is gated on it |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function offMap(model) {
  const ids = new Set(model.nodes.map((n) => n.id));
  const off = model.workflows
    .filter((w) => !ids.has(w.id))
    .map((w) => code(w.file));
  return off.length
    ? `Not on the map, because no pipeline step or label leads to them: ${off.join(', ')}. See the table.`
    : '';
}

export function renderMarkdown(model) {
  return (
    [
      '# Pipeline map',
      '<!-- Generated by tools/pipeline-map, do not edit by hand. -->',
      '> Generated by `tools/pipeline-map`, do not edit by hand. Regenerate with `pnpm pipeline:map`; `pnpm verify` fails when this file is stale.',
      'Every path through the issue → PR pipeline, derived from `.github/workflows/*.yml` and the `STAGES`, `MARKERS`, `FIX_LOOP_*` and `COMMAND_EFFECTS` exports of `.github/scripts/pipeline-lib.mjs`. The prose lives in [pipeline.md](pipeline.md).',
      '## Map',
      'Blue: stage labels. Grey: workflows; an arrow from a label into a workflow is its label gate. Red, dashed: escalations to a problem stage. Amber: humans. Teal: the fix loop.',
      offMap(model),
      '```mermaid\n' + renderMermaid(model) + '\n```',
      '## Workflows',
      workflowTable(model),
      '## Comment markers',
      markerTable(model),
      '## Stages with no label gate, by design',
      'From `EXPECTED_UNGATED` in `tools/pipeline-map/src/config.mjs`.',
      ungatedTable(model),
      '## Findings',
      model.findings.map((f) => `- ${f.text}`).join('\n'),
    ]
      .filter(Boolean)
      .join('\n\n') + '\n'
  );
}
