import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// The file length policy (docs/conventions.md, "File length"): a committed
// source, test, docs or workflow file may not be longer than the hard cap
// unless the repository owner listed it in the registry below.

const HARD_CAP_LINES = 400;
const MAX_EXCEPTION_DAYS = 90;
const MILLISECONDS_PER_DAY = 86_400_000;

/** Where the owner records exceptions; a protected path, so agents cannot add one. */
const FILE_LENGTH_REGISTRY_PATH = 'tools/security/file-length-exceptions.json';

export interface FileLengthException {
  path: string;
  issue: number;
  reason: string;
  owner: string;
  created: string;
  expires: string;
}

export interface MeasuredFile {
  path: string;
  lineCount: number;
}

/** Code, tests, docs and workflow YAML. Everything else (JSON, images, lockfiles) is out of scope. */
const CHECKED_FILE = /\.(m?[jt]sx?|cjs|cts|sh|css|mdx?)$/;
const WORKFLOW_FILE = /^\.github\/workflows\/.+\.ya?ml$/;

/** Generated or build output folders. */
const OUTPUT_FOLDERS = new Set([
  'node_modules',
  'dist',
  'out-tsc',
  'storybook-static',
  'test-output',
  '.nx',
  '.security-bin',
]);
/** Generated by `pnpm pipeline:map`. */
const GENERATED_FILES = new Set(['docs/pipeline-map.md']);
/** Copies of the Nx plugin skills: vendored third-party text. */
const VENDORED_FOLDERS = ['.agents/skills/', '.github/skills/'];

const OWNER = /^@[A-Za-z0-9-]+(\/[A-Za-z0-9-]+)?$/;
const PLACEHOLDER_OWNER =
  /^@(your-.*|owner|user|username|team|todo|tbd|example)$/i;
const DATE = /^\d{4}-\d{2}-\d{2}$/;

/** Physical lines of a file's text, as `wc -l` counts them (a last line without a newline counts). */
export function countPhysicalLines(text: string): number {
  if (text === '') return 0;
  const newlineCount = text.split('\n').length - 1;
  return text.endsWith('\n') ? newlineCount : newlineCount + 1;
}

/** True if the policy applies to this repo-relative path. */
export function isLengthChecked(path: string): boolean {
  const normalizedPath = path.replaceAll('\\', '/');
  if (normalizedPath.split('/').some((part) => OUTPUT_FOLDERS.has(part))) {
    return false;
  }
  if (GENERATED_FILES.has(normalizedPath)) return false;
  if (VENDORED_FOLDERS.some((folder) => normalizedPath.startsWith(folder))) {
    return false;
  }
  return (
    CHECKED_FILE.test(normalizedPath) || WORKFLOW_FILE.test(normalizedPath)
  );
}

const parseDay = (day: unknown): number =>
  typeof day === 'string' && DATE.test(day)
    ? Date.parse(`${day}T00:00:00Z`)
    : Number.NaN;

/** Problems with the registry's content; empty when it is valid. */
export function validateRegistry(entries: unknown, today: Date): string[] {
  if (!Array.isArray(entries)) {
    return [`${FILE_LENGTH_REGISTRY_PATH} must be a JSON array.`];
  }
  const todayMilliseconds = Date.parse(
    `${today.toISOString().slice(0, 10)}T00:00:00Z`,
  );
  const problems: string[] = [];
  const seenPaths = new Set<string>();

  entries.forEach(
    (entry: Partial<Record<keyof FileLengthException, unknown>>, index) => {
      const label = `entry ${index} (${String(entry?.path)})`;
      if (typeof entry?.path !== 'string' || entry.path === '') {
        problems.push(`${label}: path must be a repo-relative file path.`);
      } else if (seenPaths.has(entry.path)) {
        problems.push(`${label}: the path is listed twice.`);
      } else {
        seenPaths.add(entry.path);
      }
      if (!Number.isInteger(entry?.issue) || (entry?.issue as number) < 1) {
        problems.push(`${label}: issue must be an issue number.`);
      }
      if (
        typeof entry?.reason !== 'string' ||
        entry.reason.trim().length < 20
      ) {
        problems.push(`${label}: reason must be at least 20 characters.`);
      }
      const owner = typeof entry?.owner === 'string' ? entry.owner : '';
      if (PLACEHOLDER_OWNER.test(owner) || !OWNER.test(owner)) {
        problems.push(`${label}: owner must be a GitHub @user or @org/team.`);
      }
      const created = parseDay(entry?.created);
      const expires = parseDay(entry?.expires);
      if (Number.isNaN(created)) {
        problems.push(`${label}: created must be YYYY-MM-DD.`);
      } else if (created > todayMilliseconds) {
        problems.push(`${label}: created is in the future.`);
      }
      if (Number.isNaN(expires)) {
        problems.push(`${label}: expires must be YYYY-MM-DD.`);
      } else {
        if (
          !Number.isNaN(created) &&
          expires - created > MAX_EXCEPTION_DAYS * MILLISECONDS_PER_DAY
        ) {
          problems.push(
            `${label}: expires more than ${MAX_EXCEPTION_DAYS} days after created.`,
          );
        }
        if (expires < todayMilliseconds) {
          problems.push(
            `${label}: expired on ${String(entry?.expires)}; split the file.`,
          );
        }
      }
    },
  );
  return problems;
}

/**
 * Files over the cap with no registry entry, and registry entries that no
 * longer point at a file over the cap (they must be removed, so the list only
 * shrinks). `files` are the measured files in scope; call validateRegistry first.
 */
export function findFileLengthProblems(
  files: MeasuredFile[],
  registry: FileLengthException[],
): string[] {
  const registeredPaths = new Set(registry.map((entry) => entry.path));
  const problems = files
    .filter(
      (file) =>
        file.lineCount > HARD_CAP_LINES && !registeredPaths.has(file.path),
    )
    .map(
      (file) =>
        `${file.path}: ${file.lineCount} lines, over the ${HARD_CAP_LINES}-line cap. Split it (docs/conventions.md, "File length"); an exception is an entry in ${FILE_LENGTH_REGISTRY_PATH}.`,
    );

  const lineCountByPath = new Map(
    files.map((file) => [file.path, file.lineCount]),
  );
  for (const { path } of registry) {
    const lineCount = lineCountByPath.get(path);
    if (lineCount === undefined) {
      problems.push(
        `${path}: listed in the registry but not a checked file; remove the entry.`,
      );
    } else if (lineCount <= HARD_CAP_LINES) {
      problems.push(
        `${path}: listed in the registry but now ${lineCount} lines, within the cap; remove the entry.`,
      );
    }
  }
  return problems;
}

/** The registry's parsed content; a missing file is an empty registry. */
export function readRegistry(workspaceRoot: string): unknown {
  const registryFile = join(workspaceRoot, FILE_LENGTH_REGISTRY_PATH);
  return existsSync(registryFile)
    ? JSON.parse(readFileSync(registryFile, 'utf8'))
    : [];
}

/** Line counts of the committed files the policy covers, as they are on disk now. */
export function measureCommittedFiles(workspaceRoot: string): MeasuredFile[] {
  const committedPaths = execFileSync('git', ['ls-files', '-z'], {
    cwd: workspaceRoot,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
    .split('\0')
    .filter(Boolean);
  return committedPaths
    .filter(isLengthChecked)
    .filter((path) => existsSync(join(workspaceRoot, path)))
    .map((path) => ({
      path,
      lineCount: countPhysicalLines(
        readFileSync(join(workspaceRoot, path), 'utf8'),
      ),
    }));
}
