// Each case is written to a real file in the real source tree and found by the
// same tree walk that guards the app, so file selection (extensions, folders)
// is under test too, not just the scanner. The files are removed afterwards.
export const PLANTED_CASES: Array<[string, string, string, number]> = [
  [
    'a .tsx with spaces around =',
    'Planted.tsx',
    'export const Planted = () => <a href = "/x">x</a>;',
    1,
  ],
  [
    'a .tsx with a comment inside the braces',
    'Planted.tsx',
    'export const Planted = () => <a href={/* x */ "/x"}>x</a>;',
    1,
  ],
  [
    'a .tsx with ">" in an earlier attribute',
    'Planted.tsx',
    'export const Planted = () => <a title="a > b" href="/x">x</a>;',
    1,
  ],
  [
    'a .tsx tag with several src/href attributes',
    'Planted.tsx',
    'export const Planted = () => <link src="/a.js" href="/b.css" />;',
    2,
  ],
  [
    'a .ts file with a CSS url() string',
    'planted.ts',
    "export const background = 'url(/bg.png)';",
    1,
  ],
  [
    'a real .css file with url()',
    'planted.css',
    '.a { background: url(/bg.png); }',
    1,
  ],
  [
    'a real .css file with URL( and an escape',
    'planted.css',
    String.raw`.a { background: URL( "/a.png" ); } .b { background: \75rl(/b.png); }`,
    2,
  ],
  ['a real .css file with @import', 'planted.css', '@import "/other.css";', 1],
  [
    'a .tsx with a character reference for "/"',
    'Planted.tsx',
    'export const Planted = () => <a href="&#47;x">x</a>;',
    1,
  ],
  [
    'a .tsx with a hexadecimal character reference for "//"',
    'Planted.tsx',
    'export const Planted = () => <script src="&#x2F;&#x2f;cdn.test/a.js"></script>;',
    1,
  ],
  [
    'a .tsx with an empty-string prefix on a root-absolute string',
    'Planted.tsx',
    'export const Planted = () => <a href={"" + "/x"}>x</a>;',
    1,
  ],
  [
    'a .tsx with a literal prefix followed by an unknown value',
    'Planted.tsx',
    'export const Planted = ({ slug }: { slug: string }) => <a href={"" + "/" + slug}>x</a>;',
    1,
  ],
  [
    'a .tsx whose "&#47;" is inside a JS string, not a JSX attribute',
    'Planted.tsx',
    'export const Planted = () => <a href={"&#47;x"}>x</a>;',
    0,
  ],
  [
    'a .tsx that puts BASE_URL before a root-absolute string',
    'Planted.tsx',
    'export const Planted = () => <a href={import.meta.env.BASE_URL + "/x"}>x</a>;',
    0,
  ],
  [
    'a .tsx with a leading space',
    'Planted.tsx',
    'export const Planted = () => <a href=" /x">x</a>;',
    1,
  ],
  [
    'a .tsx with a leading tab and newline',
    'Planted.tsx',
    'export const Planted = () => <a href="\t\n/x">x</a>;',
    1,
  ],
  [
    'a .tsx with a leading space as a character reference',
    'Planted.tsx',
    'export const Planted = () => <a href="&#32;/x">x</a>;',
    1,
  ],
  [
    'a .tsx with a leading tab as a character reference',
    'Planted.tsx',
    'export const Planted = () => <a href="&#9;/x">x</a>;',
    1,
  ],
  [
    'a .tsx with a leading space in a JS string inside braces',
    'Planted.tsx',
    'export const Planted = () => <a href={" /x"}>x</a>;',
    1,
  ],
  [
    'a .tsx with a leading space in a literal concatenation',
    'Planted.tsx',
    'export const Planted = () => <a href={" " + "/x"}>x</a>;',
    1,
  ],
  [
    'a .tsx with a space after the BASE_URL prefix',
    'Planted.tsx',
    'export const Planted = () => <a href={import.meta.env.BASE_URL + " /x"}>x</a>;',
    0,
  ],
  [
    'a real .css file with a space inside a quoted url()',
    'planted.css',
    '.a { background: url(" /bg.png"); }',
    1,
  ],
  [
    'a real .css file with a tab inside a quoted url()',
    'planted.css',
    '.a { background: url("\t/bg.png"); }',
    1,
  ],
  [
    'a real .css file with a leading space in an @import',
    'planted.css',
    '@import " /x.css";',
    1,
  ],
  [
    'a real .css file with the tab as a CSS escape',
    'planted.css',
    String.raw`.a { background: url("\9 /bg.png"); }`,
    1,
  ],
  [
    'a .tsx with a quoted CSS url() with a leading space in a string',
    'Planted.tsx',
    'export const style = { backgroundImage: \'url(" /bg.png")\' };',
    1,
  ],
  [
    'a real .css file with a no-break space before "/"',
    'planted.css',
    '.a { background: url("\u00A0/bg.png"); }',
    0,
  ],
  [
    'a real .css file with a leading space inside a comment',
    'planted.css',
    '/* url(" /bg.png") */ .a { color: red; }',
    0,
  ],
  [
    'a .ts with a space before BASE_URL in a CSS string',
    'planted.ts',
    'export const style = `url(" ${import.meta.env.BASE_URL}bg.png")`;',
    0,
  ],
  [
    'a .tsx whose only path is in a JSX comment',
    'Planted.tsx',
    'export const Planted = () => <p>{/* <a href="/x">example</a> */}</p>;',
    0,
  ],
  [
    'a .ts whose only path is in a comment',
    'planted.ts',
    '// <img src="/x.png" /> and url(/bg.png)\nexport const value = 1;',
    0,
  ],
  [
    'a real .css file whose only url() is in a comment',
    'planted.css',
    '/* url(/bg.png) and @import "/x.css" */ .a { color: red; }',
    0,
  ],
  [
    'a .tsx that uses the base path and Link',
    'Planted.tsx',
    'export const Planted = () => <><a href={`${import.meta.env.BASE_URL}x`}>x</a><Link to="/x">x</Link></>;',
    0,
  ],
];
